// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	ns "github.com/containernetworking/plugins/pkg/ns"
	mock "github.com/stretchr/testify/mock"
)

// NS is an autogenerated mock type for the NS type
type NS struct {
	mock.Mock
}

// GetNS provides a mock function with given fields: nspath
func (_m *NS) GetNS(nspath string) (ns.NetNS, error) {
	ret := _m.Called(nspath)

	var r0 ns.NetNS
	if rf, ok := ret.Get(0).(func(string) ns.NetNS); ok {
		r0 = rf(nspath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ns.NetNS)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nspath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
