FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.10 AS builder

COPY . /usr/src/accelerated-bridge-cni

WORKDIR /usr/src/accelerated-bridge-cni
RUN make clean && \
    make build

FROM registry.svc.ci.openshift.org/ocp/4.0:base
COPY --from=builder /usr/src/accelerated-bridge-cni/build/accelerated-bridge /usr/bin/
WORKDIR /

LABEL io.k8s.display-name="ACCELERATED BRIDGE CNI"

COPY ./images/entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
