// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	types "github.com/k8snetworkplumbingwg/accelerated-bridge-cni/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// LoadConf provides a mock function with given fields: bytes, netConf
func (_m *Loader) LoadConf(bytes []byte, netConf *types.NetConf) error {
	ret := _m.Called(bytes, netConf)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, *types.NetConf) error); ok {
		r0 = rf(bytes, netConf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParseConf provides a mock function with given fields: bytes, conf
func (_m *Loader) ParseConf(bytes []byte, conf *types.PluginConf) error {
	ret := _m.Called(bytes, conf)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, *types.PluginConf) error); ok {
		r0 = rf(bytes, conf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
